### ISSUE TITLE
报错求解答

### ISSUE THREAD

**Issue by 8MiYile** [nladuo/AI_beatmap_generator#1]
> /home/bmi_yile/.local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
(3779919,)
/home/bmi_yile/.local/lib/python3.7/site-packages/librosa/core/spectrum.py:224: UserWarning: n_fft=2048 is too small for input signal of length=1200
  n_fft, y.shape[-1]
1566
/home/bmi_yile/.local/lib/python3.7/site-packages/torch/serialization.py:671: SourceChangeWarning: source code of class 'torch.nn.modules.rnn.GRU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "gen_beatmaps.py", line 128, in <module>
    encoder_ln1 = torch.load("checkpoints/encoder_ln1.pth").to(device)
  File "/home/bmi_yile/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 899, in to
    return self._apply(convert)
  File "/home/bmi_yile/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/bmi_yile/.local/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 187, in _apply
    self._flat_weights = [(lambda wn: getattr(self, wn) if hasattr(self, wn) else None)(wn) for wn in self._flat_weights_names]
  File "/home/bmi_yile/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'GRU' object has no attribute '_flat_weights_names'

**Comment by Ybr2007** [comment]
同样的报错，求解答

**Comment by dogrepairditch** [comment]
怎么办的最后 哭死 一直报错
